AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  AllowedMethods:
    - RSpec.describe
    - describe

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
